// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestaurantHelper.Models;

#nullable disable

namespace RestaurantHelper.Migrations
{
    [DbContext(typeof(RestaurantContext))]
    partial class RestaurantContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("RestaurantHelper.Models.Comanda", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<int>("MesaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<int>("Propina")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ValorFinal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ValorTotal")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MesaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Comandas");
                });

            modelBuilder.Entity("RestaurantHelper.Models.Menu", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Detalle")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<int>("Valor")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Menu", (string)null);
                });

            modelBuilder.Entity("RestaurantHelper.Models.Mesa", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ComandaActualId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ComandaActualId");

                    b.ToTable("Mesa", (string)null);
                });

            modelBuilder.Entity("RestaurantHelper.Models.PedidoComanda", b =>
                {
                    b.Property<int>("ComandaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MenuId")
                        .HasColumnType("INTEGER");

                    b.HasIndex("ComandaId");

                    b.HasIndex("MenuId");

                    b.ToTable("PedidosComanda");
                });

            modelBuilder.Entity("RestaurantHelper.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("Rut")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.HasKey("Id")
                        .HasName("PK__Usuario__3214EC07C1CD3BFD");

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("RestaurantHelper.Models.Comanda", b =>
                {
                    b.HasOne("RestaurantHelper.Models.Mesa", "Mesa")
                        .WithMany("Comandas")
                        .HasForeignKey("MesaId")
                        .IsRequired()
                        .HasConstraintName("FK_Comanda_Mesa");

                    b.HasOne("RestaurantHelper.Models.Usuario", "Usuario")
                        .WithMany("Comandas")
                        .HasForeignKey("UsuarioId")
                        .IsRequired()
                        .HasConstraintName("FK_Comanda_Usuario");

                    b.Navigation("Mesa");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("RestaurantHelper.Models.Mesa", b =>
                {
                    b.HasOne("RestaurantHelper.Models.Comanda", "ComandaActual")
                        .WithMany("Mesas")
                        .HasForeignKey("ComandaActualId")
                        .IsRequired()
                        .HasConstraintName("FK_Mesa_Comanda");

                    b.Navigation("ComandaActual");
                });

            modelBuilder.Entity("RestaurantHelper.Models.PedidoComanda", b =>
                {
                    b.HasOne("RestaurantHelper.Models.Comanda", "Comanda")
                        .WithMany()
                        .HasForeignKey("ComandaId")
                        .IsRequired()
                        .HasConstraintName("FK_PedidoComanda_Comanda");

                    b.HasOne("RestaurantHelper.Models.Menu", "Menu")
                        .WithMany()
                        .HasForeignKey("MenuId")
                        .IsRequired()
                        .HasConstraintName("FK_PedidoComanda_Menu");

                    b.Navigation("Comanda");

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("RestaurantHelper.Models.Comanda", b =>
                {
                    b.Navigation("Mesas");
                });

            modelBuilder.Entity("RestaurantHelper.Models.Mesa", b =>
                {
                    b.Navigation("Comandas");
                });

            modelBuilder.Entity("RestaurantHelper.Models.Usuario", b =>
                {
                    b.Navigation("Comandas");
                });
#pragma warning restore 612, 618
        }
    }
}
